version: "3.4"

services:
  minesweeper-api-test:
    build:
      context: .
    container_name: minesweeper-api-test
    environment:
      - NODE_ENV=testing
      - WAIT_HOSTS=minesweeper-db-test:5432
      - DB_NAME_TEST=minesweeper_db_test
      - DB_HOST=minesweeper-db-test
      - DB_PORT=5432
      - DB_PASSWORD=admin
      - DB_USER=admin
      - SESSION_SECRET_KEY=1aff451968bc0695638b119bc1c5a9bd261c90c833464ecb5def42c89c32a14ed8f63940baea1b30a9204bdd659431e3e5c8a14a19a8fe32ca279ac430675e93
    command: sh -c "/wait && npm run migrate-and-test"
    depends_on:
      - minesweeper-db-test
    networks:
      - minesweeper-test

  minesweeper-db-test:
    image: postgres:12-alpine
    container_name: minesweeper-db-test
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_PORT=5432
      - POSTGRES_DB=minesweeper_db_test
    networks:
      - minesweeper-test

networks:
  minesweeper-test:
