version: "3.4"

services:
  minesweeper-api-dev:
    build:
      context: .
    container_name: minesweeper-api-dev
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=minesweeper-db-dev:5432
      - DB_NAME_DEV=minesweeper_db_dev
      - DB_HOST=minesweeper-db-dev
      - DB_PORT=5432
      - DB_PASSWORD=admin
      - DB_USERNAME=admin
      - SESSION_SECRET_KEY=1aff451968bc0695638b119bc1c5a9bd261c90c833464ecb5def42c89c32a14ed8f63940baea1b30a9204bdd659431e3e5c8a14a19a8fe32ca279ac430675e93
    command: sh -c "/wait && npm run migrate-and-start"
    depends_on:
      - minesweeper-db-dev
    ports:
      - "8080:8080"
    networks:
      - minesweeper-dev

  minesweeper-db-dev:
    image: postgres:12-alpine
    container_name: minesweeper-db-dev
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_PORT=5432
      - POSTGRES_DB=minesweeper_db_dev
    networks:
      - minesweeper-dev

networks:
  minesweeper-dev:
